# Generated by Django 3.2 on 2021-04-20 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('thesloiks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(choices=[('PLN', 'Pln'), ('USD', 'Usd'), ('EUR', 'Eur')], default='PLN', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(choices=[('WITHDRAW', 'Withdraw'), ('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer')], max_length=8)),
                ('title', models.CharField(max_length=250)),
                ('currency', models.CharField(choices=[('PLN', 'Pln'), ('USD', 'Usd'), ('EUR', 'Eur')], default='PLN', max_length=3)),
                ('source_jar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_jar', to='thesloiks.jar')),
                ('target_jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_jar', to='thesloiks.jar')),
            ],
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, target_jar=django.db.models.expressions.F('source_jar')), name='target_jar_and_source_jar_must_be_different'),
        ),
    ]
