# Generated by Django 3.2 on 2021-04-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thesloiks', '0002_auto_20210420_2255'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='target_jar_and_source_jar_must_be_different',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AlterField(
            model_name='jar',
            name='currency',
            field=models.CharField(default='PLN', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='PLN', max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_jar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_jar', to='thesloiks.jar'),
        ),
    ]
