# Generated by Django 3.2 on 2021-04-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesloiks', '0003_auto_20210423_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='', max_length=8),
        ),
    ]
